name: Bug Report
description: Create a bug report for the Nautilus Platform

body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report!
  - type: textarea
    attributes:
      label: Summary
      description: Please provide a short summary of the bug, along with any information you feel relevant to replicate the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: Describe what you expect to happen.    
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior
      description: Describe what actually happens.    
    validations:
      required: true
  - type: textarea
    attributes:
      label:  Possible Solution
      description: Suggest a fix/reason for the bug, or ideas how to implement the addition or change. 
    validations:
      required: false
